services:
  db:
    image: postgres:14.4
    command:
      - 'postgres'
      - '-c'
      - 'search_path=public,content'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres.env
    expose:
      - 5432
    depends_on:
      - elastic
    networks:
      - backend
  etl:
    build: .
    links:
      - 'db'
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
      - elastic
    networks:
      - backend
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    volumes:
      - elacticsearch-data:/usr/share/elacticsearch/data
    expose:
      - 9200
    networks:
      - backend
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis-data:/data
    expose:
      - 6739
    networks:
      - backend

volumes:
  postgres_data:
  elacticsearch-data:
  redis-data:

networks:
  backend:
     driver: bridge